version: "3"
services:
  jupyter:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - ".:/home/jovyan/work/"
    environment:
      JUPYTER_LAB_ENABLE: "yes"
    command: ["start.sh", "jupyter", "lab"]
  flask:
    build: .
    ports:
    - "5000:5000"
    volumes:
    - ".:/home/jovyan/work/"
    command: ["python", "run.py"]
    
