version: "3.2"
services:
  jupyter:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - ".:/home/jovyan/work/"
    environment:
      JUPYTER_LAB_ENABLE: "yes"
    command: ["start.sh", "jupyter", "lab"]
  app:
    build: .
    ports:
    - "127.0.0.1:8000:8000"
    volumes:
    - ".:/home/jovyan/work/"
    command: ["gunicorn", "-w", "4", "run:app"]


