version: "3"
services:
  jupyter:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - ".:/home/jovyan/work/"
  db:
    image: postgres
    restart: always
    volumes:
    - pgdata:/var/lib/postgresql/data    
    environment:
    - POSTGRES_PASSWORD: password12345
volumes:
  pgdata:
