version: "3"
services:
  jupyter:
    build: .
    ports:
    - "8888:8888"
    volumes:
    - ".:/home/jovyan/work/"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: password12345
