name: wikidit
channels:
- conda-forge
dependencies:
- flask
- graphviz
- gunicorn
- invoke
- joblib
- jupyter
- jupyterlab
- lxml
- matplotlib
- nb_conda_kernels
- pandas=0.23.*
- python=3.6.*
- python-graphviz
- scikit-learn>=0.20.*
- seaborn
- spacy=2.0.*
- tqdm
- xgboost=0.80.*
- pip:
  - mwapi
  - mwparserfromhell
  - mwxml
  # conda- "https://github.com/explosion/spacy-models/releases/download/en_core_web_md-1.2.0/en_core_web_md-1.2.0.tar.gz"
