name: wikidit
channels:
- conda-forge
dependencies:
- python=3.6
- flask
- gunicorn
- invoke
- joblib
- lxml
- pandas=0.23
- plotly
- scikit-learn>=0.20
- spacy=2.0
- smart_open
- tqdm
- xgboost=0.80
- pip:
  - cssselect
  - mwapi
  - mwparserfromhell
  - mwxml
  - sklearn-pandas
  - yarl
  - git+https://github.com/jrnold/sklearn-ordinal.git
