name: wikidit
channels:
- conda-forge
dependencies:
- flask
- graphviz
- gunicorn
- invoke
- joblib
- jupyter
- jupyterlab
- lxml
- matplotlib
- nb_conda_kernels
- pandas=0.23.*
- plotly
- python=3.6.*
- scikit-learn>=0.20.*
- seaborn
- spacy=2.0.*
- smart_open
- tqdm
- xgboost=0.80.*
- pip:
  - cssselect
  - mwapi
  - mwparserfromhell
  - mwxml
  - sklearn-pandas
  - yarl
  - git+https://github.com/jrnold/sklearn-ordinal.git
